### ISSUE TITLE
Server crash in Spawner

### ISSUE THREAD

**Issue by allaryin** [allaryin/FairyFactions#15]
```
java.lang.NoSuchMethodError: net.minecraft.block.Block.func_149637_q()Z
        at fairies.world.Spawner.canCreatureTypeSpawnAtLocation(Spawner.java:626)
        at fairies.world.Spawner.doCustomSpawning(Spawner.java:332)
        at fairies.world.Spawner.onTick(Spawner.java:100)
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_14_Spawner_onTick_WorldTickEvent.invoke(.dynamic)
        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
        at cpw.mods.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:255)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:645)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
```

**Comment by allaryin** [comment]
Had same issue in EntityFairy, search didn't find it on first pass :P

```
net.minecraft.util.ReportedException: Ticking entity
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:642) ~[MinecraftServer.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) ~[lt.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) ~[MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
Caused by: java.lang.NoSuchMethodError: net.minecraft.block.Block.func_149637_q()Z
    at fairies.entity.EntityFairy.func_70094_T(EntityFairy.java:430) ~[EntityFairy.class:?]
    at net.minecraft.entity.EntityLivingBase.func_70030_z(EntityLivingBase.java:196) ~[sv.class:?]
    at net.minecraft.entity.EntityLiving.func_70030_z(EntityLiving.java:157) ~[sw.class:?]
    at net.minecraft.entity.Entity.func_70071_h_(Entity.java:318) ~[sa.class:?]
    at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1561) ~[sv.class:?]
    at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:206) ~[sw.class:?]
    at fairies.entity.EntityFairy.func_70071_h_(EntityFairy.java:262) ~[EntityFairy.class:?]
    at net.minecraft.world.World.func_72866_a(World.java:2070) ~[ahb.class:?]
    at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648) ~[mt.class:?]
    at net.minecraft.world.World.func_72870_g(World.java:2034) ~[ahb.class:?]
    at net.minecraft.world.World.func_72939_s(World.java:1887) ~[ahb.class:?]
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489) ~[mt.class:?]
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636) ~[MinecraftServer.class:?]
    ... 4 more
```
