### ISSUE TITLE
Setting Fairy to Fish on SMP caused server crash

### ISSUE THREAD

**Issue by KaesBuerschtl** [allaryin/FairyFactions#26]
Hello!
I am running a 1.7.10 server with Fairy Factions 0.5.2a Today I had a user capture some fairies and apparently they set one or more to go fishing. Shortly after this, the server crashed. In the logs is the following stack trace, please let me know if any additional information is needed, thanks!

[00:10:46] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking entity
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:642) ~[MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) ~[lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
Caused by: java.lang.NoSuchMethodError: net.minecraft.block.Block.func_149637_q()Z
        at fairies.ai.FairyJob.getToLand(FairyJob.java:652) ~[FairyJob.class:?]
        at fairies.ai.FairyJob.onFishingUse(FairyJob.java:593) ~[FairyJob.class:?]
        at fairies.ai.FairyJob.checkChestItem(FairyJob.java:284) ~[FairyJob.class:?]
        at fairies.ai.FairyJob.getNearbyChest2(FairyJob.java:190) ~[FairyJob.class:?]
        at fairies.ai.FairyJob.discover(FairyJob.java:59) ~[FairyJob.class:?]
        at fairies.entity.EntityFairy.handlePosted(EntityFairy.java:1633) ~[EntityFairy.class:?]
        at fairies.entity.EntityFairy.func_70626_be(EntityFairy.java:702) ~[EntityFairy.class:?]
        at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:1780) ~[sv.class:?]
        at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:367) ~[sw.class:?]
        at net.minecraft.entity.EntityAgeable.func_70636_d(SourceFile:95) ~[rx.class:?]
        at net.minecraft.entity.passive.EntityAnimal.func_70636_d(SourceFile:37) ~[wf.class:?]
        at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1611) ~[sv.class:?]
        at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:206) ~[sw.class:?]
        at fairies.entity.EntityFairy.func_70071_h_(EntityFairy.java:265) ~[EntityFairy.class:?]
        at net.minecraft.world.World.func_72866_a(World.java:2070) ~[ahb.class:?]
        at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648) ~[mt.class:?]
        at net.minecraft.world.World.func_72870_g(World.java:2034) ~[ahb.class:?]
        at net.minecraft.world.World.func_72939_s(World.java:1887) ~[ahb.class:?]
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489) ~[mt.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636) ~[MinecraftServer.class:?]
        ... 4 more

**Comment by allaryin** [comment]
That's odd. It looks like what probably happened was that the fairy was in the water when it noticed the sign and decided to start fishing... this isn't a case I had tested. I'll try to have a patch for this tomorrow.

**Comment by baudtack** [comment]
Same issue here.

[15:03:50] [Server thread/INFO] [FairyFactions]: setRulerName: 1586 = baudtack
[15:03:50] [Server thread/INFO] [FairyFactions]: setRulerName: 1588 = baudtack
[15:03:50] [Server thread/INFO] [FairyFactions]: setRulerName: 1589 = baudtack
[15:03:50] [Server thread/INFO] [FairyFactions]: setRulerName: 1590 = baudtack
[15:03:50] [Server thread/INFO] [FairyFactions]: setRulerName: 1591 = baudtack
[15:03:51] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking entity
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:642) ~[MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) ~[lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
Caused by: java.lang.NoSuchMethodError: net.minecraft.block.Block.func_149637_q()Z
        at fairies.ai.FairyJob.getToLand(FairyJob.java:652) ~[FairyJob.class:?]
        at fairies.ai.FairyJob.onFishingUse(FairyJob.java:593) ~[FairyJob.class:?]
        at fairies.ai.FairyJob.checkChestItem(FairyJob.java:284) ~[FairyJob.class:?]
        at fairies.ai.FairyJob.getNearbyChest2(FairyJob.java:190) ~[FairyJob.class:?]
        at fairies.ai.FairyJob.discover(FairyJob.java:59) ~[FairyJob.class:?]
        at fairies.entity.EntityFairy.handlePosted(EntityFairy.java:1633) ~[EntityFairy.class:?]
        at fairies.entity.EntityFairy.func_70626_be(EntityFairy.java:702) ~[EntityFairy.class:?]
        at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:1780) ~[sv.class:?]
        at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:367) ~[sw.class:?]
        at net.minecraft.entity.EntityAgeable.func_70636_d(SourceFile:95) ~[rx.class:?]
        at net.minecraft.entity.passive.EntityAnimal.func_70636_d(SourceFile:37) ~[wf.class:?]
        at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1611) ~[sv.class:?]
        at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:206) ~[sw.class:?]
        at fairies.entity.EntityFairy.func_70071_h_(EntityFairy.java:265) ~[EntityFairy.class:?]
        at net.minecraft.world.World.func_72866_a(World.java:2070) ~[ahb.class:?]
        at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648) ~[mt.class:?]
        at net.minecraft.world.World.func_72870_g(World.java:2034) ~[ahb.class:?]
        at net.minecraft.world.World.func_72939_s(World.java:1887) ~[ahb.class:?]
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489) ~[mt.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636) ~[MinecraftServer.class:?]
        ... 4 more
[15:03:51] [Server thread/ERROR]: This crash report has been saved to: /home/baudtack/mc/./crash-reports/crash-2016-06-04_15.03.51-server.txt
[15:03:51] [Server thread/INFO]: Stopping server
[15:03:51] [Server thread/INFO]: Saving players
[15:03:51] [Server thread/INFO]: Saving worlds
[15:03:51] [Server thread/INFO]: Saving chunks for level 'world'/Overworld
[15:03:51] [Server thread/INFO] [STDOUT]: [atomicstryker.ruins.common.ChunkLoggerData:func_76184_a:24]: Ruins chunks logged: 12292
[15:03:51] [Server thread/INFO]: Saving chunks for level 'world'/Nether
[15:03:51] [Server thread/INFO]: Saving chunks for level 'world'/The End
[15:03:51] [Server thread/INFO]: Saving chunks for level 'world'/Wyvern Lair
[15:03:51] [Server thread/INFO] [FML]: Unloading dimension 0
[15:03:51] [Server thread/INFO] [FML]: Unloading dimension -1
[15:03:51] [Server thread/INFO] [FML]: Unloading dimension 1
[15:03:51] [Server thread/INFO] [FML]: Unloading dimension -17
[15:03:51] [Server thread/INFO] [FML]: Applying holder lookups
[15:03:51] [Server thread/INFO] [FML]: Holder lookups applied
[15:03:51] [Server thread/INFO] [Galacticraft]: Unregistered Dimension: -30
[15:03:51] [Server thread/INFO] [Galacticraft]: Unregistered Dimension: -29
[15:03:51] [Server thread/INFO] [Galacticraft]: Unregistered Dimension: -28
[15:03:51] [Server thread/INFO] [FML]: The state engine was in incorrect state SERVER_STOPPING and forced into state SERVER_STOPPED. Errors may have been discarded.
